### ISSUE TITLE
Directory Layout

### ISSUE THREAD

**Issue by sivakumarf22** [f22labs/rn-boilerplate#7]
This is a suggested directory layout for better modularization of projects

Directory layout
*****************

**App/Components** — Contains the presentational components

**App/Containers** : Application screens - components that compose the      presentational components

**App/Config** : Configs for the Application (e.g.: locale, env, Aws etc)

**App/Assets:**  assets like image, fonts etc :

**App/Navigator** : navigators (along with a text file describing the routes as a flowchart)

**App/hooks**: custom hooks used by the application

**App/Services:** application services (API clients , providers, context)

**App/theme** :  Base style for the application.

**Comment by ganeshf22** [comment]
Hi @sivakumarf22 , we are using the same structure suggested here. Instead of components and containers , we are using components and screens
